name: 'Build svg and deploy on GitHub Releases'
    
on:
  push:
    tags: '*'
    branches-ignore:
      - 'autodelivery**'
      - 'bump-**'
      - 'renovate/**'
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
      - 'LICENSE'
      - 'renovate.json'
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  compile:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.ref, 'main')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }} 
    
      - name: Setup Node
        run: |
            sudo apt update
            sudo npm cache clean -f
            sudo npm install -g n
            sudo n 20.17
      
      - name: Install Inkscape
        run: |
          sudo apt-get update
          sudo apt-get install -y inkscape

      - name: Generate PDFs from SVGs
        run: |
          for file in *.svg; do
            inkscape --export-type=pdf "$file"
          done
            # Checkout the repository
     
      - name: Release
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            npm install
            npx semantic-release